name: Bug report 🐛
description: Report a bug with a Brightlayer UI resource
title: '[Bug]: '
labels: ['type: bug 🐞', 'status: needs-review', 'brightlayer-ui']
assignees: []
body:
  - type: markdown
    attributes:
      value: '## Welcome!'
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report.
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) are you experiencing the issue?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Tell us more about the problem that you're running into"
      placeholder: What did you see? What did you expect to see?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description:
        'How do we reproduce the error you described above? Or any screenshots / screen recording'
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Your environment information
      description:
        'Describe any relevant environment information (e.g., Operating System, Library version number, browser used, etc.) where the issue was discovered'
    validations:
      required: false
  - type: textarea
    id: fix
    attributes:
      label: Suggested fix
      description:
        'If you have a suggestion for what might be causing the issue or where to look as a starting point, please mention it here'
    validations:
      required: false


