blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://app-etnblc-bluidocs-window-tst-eus-p01.azurewebsites.net/
    about: Check the documentation before creating an issue. It may have the answer to your question.