const PREFIX = '@DOC-IT//';

export const CHANGE_PAGE_TITLE = `${PREFIX}CHANGE-PAGE-TITLE`;
export const CHANGE_COLOR_FORMAT = `${PREFIX}CHANGE-COLOR-FORMAT`;
export const TOGGLE_DRAWER = `${PREFIX}TOGGLE_DRAWER`;
export const TOGGLE_SEARCH = `${PREFIX}TOGGLE_SEARCH`;
export const SELECT_ICON = `${PREFIX}SELECT_ICON`;
export const SET_ICON_SEARCH = `${PREFIX}SET_ICON_SEARCH`;
